[features]
resolution = true
skip-lint = false

[programs.localnet]
haio_vesting = "Haio3oNYt8MtL9traoQNJ9RXK1XEVaQBBrZZKXt2VXjz"

[programs.devnet]
haio_vesting = "Haio3oNYt8MtL9traoQNJ9RXK1XEVaQBBrZZKXt2VXjz"

[programs.mainnet]
haio_vesting = "Haio3oNYt8MtL9traoQNJ9RXK1XEVaQBBrZZKXt2VXjz"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
#cluster = "devnet"
cluster = "mainnet"

wallet = "/Users/nike/.config/solana/keypairs/haio-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/haio-vesting.ts'"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false